#!/data/data/com.termux/files/usr/bin/bash

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

clear

case $1 in
	"start")
		sshd;
		printf "SSH ${grn}Start${end}\n";
	;;

	"stop")
		pkill -9 sshd
		printf "Server ${red}Stop${end}\n"
	;;

	"status")
		if pidof sshd >/dev/null
		then
			printf "SSH ${grn}Running${end}\n";
		else
			printf "SSH ${red}Stop${end}\n";
		fi
	;;
	"install")
		pkg update
                pkg upgrade
                pkg install -y nano
                pkg install -y python
                pkg install -y git
		pkg install -y curl
		pkg install -y php
		pkg install -y openssh
		ln -s /data/data/com.termux/files/home/termux/server /data/data/com.termux/files/usr/bin/server
	;;
	"install-key")
		git clone https://github.com/karjok/terkey
		cd terkey
		python terkey.py
	;;
	"install-zsh")
		sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
	;;
	"install-zshauto")
		source ~/.zshrc
		git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
		#nano .zshrc
		sed -i 's|plugins=(git)|plugins=(git zsh-autosuggestions)|' ~/.zshrc
		#printf "nano .zshrc\nzsh-autosuggestions\n";
	;;
	"token")
		printf "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";
	;;
	*)
		printf "1. start\n";
		printf "2. stop\n";
		printf "3. status\n";
		printf "4. install\n";
		printf "5. install-key\n";
		printf "6. install-zsh\n";
		printf "7. install-zshauto\n";
	;;
esac

printf "\n";

